# Add to your existing _config.yml
collections:
  cyberpunk:
    output: true
    permalink: /cyberpunk/:slug
  horror:
    output: true
    permalink: /horror/:slug
  modern_warfare:
    output: true
    permalink: /modern-warfare/:slug
  philosophy:
    output: true
    permalink: /philosophy/:slug
  politics:
    output: true
    permalink: /politics/:slug
  talk_of_town:
    output: true
    permalink: /talk-of-town/:slug

defaults:
  - scope:
      path: ""
      type: "cyberpunk"
    values:
      layout: "post"
      genre: "cyberpunk"
  - scope:
      path: ""
      type: "horror"
    values:
      layout: "post"
      genre: "horror"
  # Repeat for all genres...
